# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_title', models.CharField(max_length=100)),
                ('content_path', models.FilePathField()),
                ('viewed', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
