# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('revise_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
    ]
