# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0002_article_page_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
