# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0006_auto_20170115_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='is_recommended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.Recommended_article'),
        ),
    ]
