# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0007_auto_20170115_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='recommended_article',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webPage.Article'),
        ),
    ]
