# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0012_auto_20170115_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
