# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0013_remove_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
