# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0014_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
