# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0017_auto_20170115_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='revise_time',
            field=models.DateTimeField(),
        ),
    ]
