# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0018_auto_20170124_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_cover',
            field=models.BooleanField(default=False),
        ),
    ]
