# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0019_article_has_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_name',
            field=models.CharField(default=b'a', max_length=100),
        ),
    ]
