# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0021_auto_20170208_0644'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Cheet_sheet_item',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('content', models.TextField(blank=True)),
    #             ('name', models.CharField(max_length=100, unique=True)),
    #             ('url_name', models.CharField(max_length=100, unique=True)),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='Cheet_sheet_project',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('project_id', models.IntegerField(unique=True)),
    #             ('name', models.CharField(max_length=100, unique=True)),
    #             ('url_name', models.CharField(max_length=100, unique=True)),
    #         ],
    #     ),
    #     migrations.AddField(
    #         model_name='cheet_sheet_item',
    #         name='project',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webPage.Cheet_sheet_project'),
    #     ),
    # ]
