# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0022_auto_20170505_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheet_sheet_project',
            name='project_id',
        ),
    ]
